# Generated by Django 5.1.2 on 2024-12-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('property_type', models.CharField(max_length=50)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bedrooms', models.IntegerField()),
                ('bathrooms', models.IntegerField()),
                ('max_guests', models.IntegerField()),
                ('rating', models.FloatField(default=0.0)),
                ('checkin', models.CharField(max_length=20)),
                ('checkout', models.CharField(max_length=20)),
                ('guest', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
        migrations.DeleteModel(
            name='Registration_details',
        ),
    ]
