# Generated by Django 5.1.2 on 2025-04-30 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amenity',
            name='properties',
        ),
        migrations.DeleteModel(
            name='Registrations_details',
        ),
        migrations.DeleteModel(
            name='Amenity',
        ),
    ]
