# Generated by Django 5.1.2 on 2025-04-30 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0008_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookings',
        ),
    ]
