# Generated by Django 5.1.2 on 2025-05-02 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0009_delete_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='owner',
            field=models.CharField(default='ayush', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='owner_pic',
            field=models.ImageField(default='room.jpeg', upload_to='owner/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='property',
            name='reviews',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='property',
            name='bathrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='property',
            name='max_guests',
            field=models.PositiveIntegerField(),
        ),
    ]
