# Generated by Django 5.1.2 on 2025-05-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0010_property_owner_property_owner_pic_property_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_host',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='owner/'),
        ),
    ]
