# Generated by Django 5.1.2 on 2025-05-03 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0012_alter_userprofile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='reviews',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
