# Generated by Django 5.1.2 on 2025-05-06 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0015_property_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='location_embed',
            field=models.TextField(blank=True, null=True),
        ),
    ]
